// MTE MK1 (la Churrera) v5.0
// Copyleft 2010-2014, 2020 by the Mojon Twins

// Generated by The Librarian v2.1 20200823
// Copyleft 2020 by The Mojon Twins

typedef struct {
    unsigned char ramPage;
    unsigned int ramOffset;
} RESOURCE;

RESOURCE resources [] = {
    { 3, 0xC000 },
    { 3, 0xC740 },
    { 3, 0xCE5A },
    { 3, 0xD573 },
    { 3, 0xDC6D },
    { 3, 0xE120 },
    { 3, 0xE5A6 },
    { 3, 0xE9E8 },
    { 3, 0xED21 },
    { 3, 0xEF0B }
};

#define C_LEVEL1_BIN                    0
#define C_LEVEL4_BIN                    1
#define C_LEVEL2_BIN                    2
#define C_LEVEL3_BIN                    3
#define RAM3_UBHRES_BIN                 4
#define RAM3_FINAL_BIN                  5
#define RAM3_SHEET_BIN                  6
#define RAM3_MENU_BIN                   7
#define RAM3_MARCADOR_BIN               8
#define RAM3_MOJON_TWINS_BIN            9

