// MTE MK1 (la Churrera) v5.0
// Copyleft 2010-2014, 2020 by the Mojon Twins

// Generated by The Librarian v2.1 20200823
// Copyleft 2020 by The Mojon Twins

typedef struct {
    unsigned char ramPage;
    unsigned int ramOffset;
} RESOURCE;

RESOURCE resources [] = {
    { 3, 0xC000 },
    { 3, 0xC70F },
    { 3, 0xCDE5 },
    { 3, 0xD4B9 },
    { 3, 0xDB75 },
    { 3, 0xE028 },
    { 3, 0xE4AE },
    { 3, 0xE8F0 },
    { 3, 0xEC29 },
    { 3, 0xEE13 }
};

#define C_LEVEL1_BIN                    0
#define C_LEVEL4_BIN                    1
#define C_LEVEL2_BIN                    2
#define C_LEVEL3_BIN                    3
#define RAM3_UBHRES_BIN                 4
#define RAM3_FINAL_BIN                  5
#define RAM3_SHEET_BIN                  6
#define RAM3_MENU_BIN                   7
#define RAM3_MARCADOR_BIN               8
#define RAM3_MOJON_TWINS_BIN            9

