// MTE MK1 (la Churrera) v5.0
// Copyleft 2010-2014, 2020 by the Mojon Twins

// Generated by The Librarian v2.1 20200823
// Copyleft 2020 by The Mojon Twins

typedef struct {
    unsigned char ramPage;
    unsigned int ramOffset;
} RESOURCE;

RESOURCE resources [] = {
    { 3, 0xC000 },
    { 3, 0xC762 },
    { 3, 0xCEA9 },
    { 3, 0xD5E7 },
    { 3, 0xDCEC },
    { 3, 0xE12C },
    { 3, 0xE542 },
    { 3, 0xE958 },
    { 3, 0xEC59 },
    { 3, 0xEE18 }
};

#define C_LEVEL2_BIN                    0
#define C_LEVEL4_BIN                    1
#define C_LEVEL3_BIN                    2
#define C_LEVEL1_BIN                    3
#define RAM3_FINAL_BIN                  4
#define RAM3_UBHRES_BIN                 5
#define RAM3_SHEET_BIN                  6
#define RAM3_MENU_BIN                   7
#define RAM3_MARCADOR_BIN               8
#define RAM3_MOJON_TWINS_BIN            9

